owner: KimuSoft 
repo: uptime 

sites:
  - name: Kimustory
    url: https://kimustory.net
  - name: Danoo
    url: http://danoo.kimustory.net/
  - name: Yp Bot
    url: https://yp.kimustory.net/
  - name: Dictionary
    url: https://dict.kimustory.net/
  - name: Archhive
    url: https://archhive.kimustory.net/
  - name: Sound Gallery
    url: https://music.kimustory.net/
  - name: Muvel
    url: https://muvel.app
  - name: Account
    url: https://accounts.kimustory.net

status-website:
  cname: uptime.kimustory.net
  logoUrl: https://kimustory.net/logo.svg
  name: Kimustory Uptime
  introTitle: "키뮤스토리 업타임"
  introMessage: "**키뮤스토리**에서 만든 서비스들의 업타임을 확인해봐요!"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
  
